export const budgetCategories = ["Bank Fees",  "Community", "Food and Drink", "Healthcare", "Interest", "Payment", "Recreation", "Service", "Shops", "Tax", "Transfer", "Travel"];
export const budgetSubCategories = {
    "Bank Fees": ["Overall","Overdraft", "ATM", "Late Payment", "Fraud Dispute", "Foreign Transaction", "Wire Transfer", "Insufficient Funds", "Cash Advance", "Excess Activity"],
    "Community": ["Overall","Animal Shelter", "Assisted Living Services", "Cemetery", "Courts", "Day Care and Preschools", "Disabled Persons Services", "Drug and Alcohol Services", "Education", "Government Departments and Agencies", "Government Lobbyists", "Housing Assistance and Shelters", "Law Enforcement", "Libraries", "Military", "Organizations and Associations", "Post Offices", "Public and Social Services", "Religious", "Senior Citizen Services"],
    "Food and Drink": ["Overall","Bar", "Breweries", "Internet Cafes", "Nightlife", "Restaurants"],
    "Healthcare": ["Overall","Healthcare Services", "Physicians"],
    "Interest": ["Overall","Interest Earned", "Interest Charged"],
    "Payment": ["Overall","Credit Card", "Rent", "Loan"],
    "Recreation": ["Overall","Arts and Entertainment", "Athletic Fields", "Baseball", "Basketball", "Batting Cages", "Boating", "Campgrounds and RV Parks", "Canoes and Kayaks", "Combat Sports", "Cycling", "Dance", "Equestrian", "Football", "Go Carts", "Golf", "Gun Ranges", "Gymnastics", "Gyms and Fitness Centers", "Hiking", "Hockey", "Hot Air Balloons", "Hunting and Fishing", "Landmarks", "Miniature Golf", "Outdoors", "Paintball", "Parks", "Personal Trainers", "Race Tracks", "Racquet Sports", "Racquetball", "Rafting", "Recreation Centers", "Rock Climbing", "Running", "Scuba Diving", "Skating", "Skydiving", "Snow Sports", "Soccer", "Sports and Recreation Camps", "Sports Clubs", "Stadiums and Arenas", "Swimming", "Tennis", "Water Sports", "Yoga and Pilates", "Zoo"],
    "Service": ["Overall","Advertising and Marketing", "Art Restoration", "Audiovisual", "Automation and Control Systems", "Automotive", "Business and Strategy Consulting", "Business Services", "Cable", "Chemicals and Gasses", "Cleaning", "Computers", "Construction", "Credit Counseling and Bankruptcy Services", "Dating and Escort", "Employment Agencies", "Engineering", "Entertainment", "Events and Event Planning", "Financial", "Food and Beverage", "Funeral Services", "Geological", "Home Improvement", "Household", "Human Resources", "Immigration", "Import and Export", "Industrial Machinery and Vehicles", "Insurance", "Internet Services", "Leather", "Legal", "Logging and Sawmills", "Machine Shops", "Management", "Manufacturing", "Media Production", "Metals", "Mining", "News Reporting", "Oil and Gas", "Packaging", "Paper", "Personal Care", "Petroleum", "Photography", "Plastics", "Rail", "Real Estate", "Refrigeration and Ice", "Renewable Energy", "Repair Services", "Research", "Rubber", "Scientific", "Security and Safety", "Shipping and Freight", "Software Development", "Storage", "Subscription", "Tailors", "Telecommunication Services", "Textiles", "Tourist Information and Services", "Transportation", "Travel Agents and Tour Operators", "Utilities", "Veterinarians", "Water and Waste Management", "Web Design and Development", "Welding", "Agriculture and Forestry", "Art and Graphic Design"],
    "Shops": ["Overall","Adult", "Antiques", "Arts and Crafts", "Auctions", "Automotive", "Beauty Products", "Bicycles", "Boat Dealers", "Bookstores", "Cards and Stationery", "Children", "Clothing and Accessories", "Computers and Electronics", "Construction Supplies", "Convenience Stores", "Costumes", "Dance and Music", "Department Stores", "Digital Purchase", "Discount Stores", "Electrical Equipment", "Equipment Rental", "Flea Markets", "Florists", "Food and Beverage Store", "Fuel Dealer", "Furniture and Home Decor", "Gift and Novelty", "Glasses and Optometrist", "Hardware Store", "Hobby and Collectibles", "Industrial Supplies", "Jewelry and Watches", "Luggage", "Marine Supplies", "Music, Video and DVD", "Musical Instruments", "Newsstands", "Office Supplies", "Outlet", "Pawn Shops", "Pets", "Pharmacies", "Photos and Frames", "Shopping Centers and Malls", "Sporting Goods", "Supermarkets and Groceries", "Tobacco", "Toys", "Vintage and Thrift", "Warehouses and Wholesale Stores", "Wedding and Bridal", "Wholesale", "Lawn and Garden"],
    "Tax": ["Overall","Refund", "Payment"],
    "Transfer": ["Overall","Internal Account Transfer", "ACH", "Billpay", "Check", "Credit", "Debit", "Deposit", "Keep the Change Savings Program", "Payroll", "Third Party", "Wire", "Withdrawal", "Save As You Go"],
    "Travel": ["Overall","Airlines and Aviation Services", "Airports", "Boat", "Bus Stations", "Car and Truck Rentals", "Car Service", "Charter Buses", "Cruises", "Gas Stations", "Heliports", "Limos and Chauffeurs", "Lodging", "Parking", "Public Transportation Services", "Rail", "Taxi", "Tolls and Fees", "Transportation Centers"]
};
